/* Generated USB host configuration for hurricane_lpc55s69 */
#ifndef USB_HOST_CONFIG_H
#define USB_HOST_CONFIG_H

#define USB_HOST_CONFIG_MAX_POWER (500U)
#define USB_HOST_CONFIG_MAX_INTERFACES (5U)
#define USB_HOST_CONFIG_MAX_ENDPOINTS (8U)
#define USB_HOST_CONFIG_MAX_DEVICES (8U)
#define USB_HOST_CONFIG_HUB (0U)
#define USB_HOST_CONFIG_CDC (0U)
#define USB_HOST_CONFIG_MSC (0U)
#define USB_HOST_CONFIG_BUFFER_PROPERTY_CACHEABLE (0U)
#define USB_HOST_CONFIG_INTERFACE_MAX_EP (8U)

#endif /* USB_HOST_CONFIG_H */
