#ifndef USB_DEVICE_CONFIG_H
#define USB_DEVICE_CONFIG_H

#define USB_DEVICE_CONFIG_LPCIP3511FS      (1U)
#define USB_DEVICE_CONFIG_LPCIP3511HS      (0U)
#define USB_DEVICE_CONFIG_EHCI             (0U)
#define USB_DEVICE_CONFIG_CONTROLLER_ID    kUSB_ControllerLpcIp3511Fs0
#define USB_DEVICE_CONFIG_INTERFACES       (2U)
#define USB_DEVICE_CONFIG_STRING_COUNT     (4U)
#define USB_DEVICE_CONFIG_ENDPOINTS        (8U)
#define USB_DEVICE_CONFIG_HID              (1U)
#define USB_DEVICE_CONFIG_SELF_POWER       (0U)
#define USB_DEVICE_CONFIG_DETACH_ENABLE    (0U)
#define USB_DEVICE_CONFIG_MAX_POWER        (100U)

#endif /* USB_DEVICE_CONFIG_H */
