/* Generated USB device configuration for hurricane_lpc55s69 */
#ifndef USB_DEVICE_CONFIG_H
#define USB_DEVICE_CONFIG_H

#define USB_DEVICE_CONFIG_EHCI (1U)
#define USB_DEVICE_CONFIG_MAX_POWER (500U)
#define USB_DEVICE_CONFIG_SELF_POWER (0U)
#define USB_DEVICE_CONFIG_DETACH_ENABLE (0U)
#define USB_DEVICE_CONFIG_ENDPOINTS (8U)
#define USB_DEVICE_CONFIG_HID (1U)
#define USB_DEVICE_CONFIG_CDC_ACM (0U)
#define USB_DEVICE_CONFIG_MSC (0U)
#define USB_DEVICE_CONFIG_AUDIO (0U)
#define USB_DEVICE_CONFIG_PHDC (0U)
#define USB_DEVICE_CONFIG_VIDEO (0U)
#define USB_DEVICE_CONFIG_BUFFER_PROPERTY_CACHEABLE (0U)
#define USB_DEVICE_CONFIG_CHARGER_DETECT (0U)

#endif /* USB_DEVICE_CONFIG_H */
