name: PlatformIO Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache PlatformIO dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.platformio
          ~/.cache/pip
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-

    - name: Install PlatformIO Core
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        echo "$HOME/.platformio/penv/bin" >> $GITHUB_PATH

    - name: Build ESP32 firmware
      run: |
        pio run -e esp32-s3-devkitc-1

    - name: Build Teensy firmware
      run: |
        pio run -e teensy41

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: |
          .pio/build/esp32-s3-devkitc-1/firmware.bin
          .pio/build/teensy41/firmware.hex